import { WebsiteRoutePath } from 'shared/modules/website'

export const MAIN_ROUTE_PATH = `${WebsiteRoutePath}/admin`
export const MAIN_ROUTE_NAME = 'HOMEBUILDER'

export const LAYOUT_PACKAGE_MASTER = 'HOMEBUILDER@LAYOUT_PACKAGE_MASTER'
export const LAYOUT_PROJECT_MASTER = 'HOMEBUILDER@LAYOUT_PROJECT_MASTER'
export const BASE_MASTER = 'HOMEBUILDER@LAYOUT_BASE_MASTER'
export const MENU_HEADER = 'HOMEBUILDER@MENU_HEADER'

//#region Product
export const PRODUCT_MENU_SIDER = 'HOMEBUILDER@PRODUCT_MENU_SIDER'
export const PRODUCT = 'HOMEBUILDER@ROUTE_PRODUCT'
export const PRODUCT_INDEX = 'HOMEBUILDER@PRODUCT_INDEX'
export const PRODUCT_NEW = 'HOMEBUILDER@ROUTE_PRODUCT_NEW'
export const PRODUCT_UPDATE = 'HOMEBUILDER@ROUTE_PRODUCT_UPDATE'
export const PRODUCT_LAYOUT_MASTER = 'HOMEBUILDER@PRODUCT_LAYOUT_MASTER'
//endregion

//#region BLOG
export const BLOG_MENU_SIDER = 'HOMEBUILDER@BLOG_MENU_SIDER'
export const BLOG = 'HOMEBUILDER@ROUTE_BLOG'
export const BLOG_INDEX = 'HOMEBUILDER@BLOG_INDEX'
export const BLOG_NEW = 'HOMEBUILDER@ROUTE_BLOG_NEW'
export const BLOG_UPDATE = 'HOMEBUILDER@ROUTE_BLOG_UPDATE'
export const BLOG_LAYOUT_MASTER = 'HOMEBUILDER@BLOG_LAYOUT_MASTER'

//# PACKAGE
export const PACKAGE_MENU_SIDER = 'HOMEBUILDER@PACKAGE_MENU_SIDER'
export const PACKAGE = 'HOMEBUILDER@ROUTE_PACKAGE'
export const PACKAGE_INDEX = 'HOMEBUILDER@PACKAGE_INDEX'
export const PACKAGE_NEW = 'HOMEBUILDER@ROUTE_PACKAGE_NEW'
export const PACKAGE_UPDATE = 'HOMEBUILDER@ROUTE_PACKAGE_UPDATE'

//# PROJECT
export const PROJECT_MENU_SIDER = 'HOMEBUILDER@PROJECT_MENU_SIDER'
export const PROJECT = 'HOMEBUILDER@PROJECT'
export const PROJECT_INDEX = 'HOMEBUILDER@PROJECT_INDEX'
export const PROJECT_NEW = 'HOMEBUILDER@PROJECT_NEW'
export const PROJECT_UPDATE = 'HOMEBUILDER@PROJECT_UPDATE'