import { WebsiteRoutePath } from 'shared/modules/website'

export const MAIN_ROUTE_PATH = `${WebsiteRoutePath}/homebuilder`
export const MAIN_ROUTE_NAME = 'HOMEBUILDER'

export const LAYOUT_PACKAGE_MASTER = 'HOMEBUILDER@LAYOUT_PACKAGE_MASTER'
export const LAYOUT_PROJECT_MASTER = 'HOMEBUILDER@LAYOUT_PROJECT_MASTER'

export const MENU_HEADER = 'HOMEBUILDER@MENU_HEADER'

//# PACKAGE
export const PACKAGE_MENU_SIDER = 'HOMEBUILDER@PACKAGE_MENU_SIDER'
export const PACKAGE = 'HOMEBUILDER@ROUTE_PACKAGE'
export const PACKAGE_INDEX = 'HOMEBUILDER@PACKAGE_INDEX'
export const PACKAGE_NEW = 'HOMEBUILDER@ROUTE_PACKAGE_NEW'
export const PACKAGE_UPDATE = 'HOMEBUILDER@ROUTE_PACKAGE_UPDATE'

//# PROJECT
export const PROJECT_MENU_SIDER = 'HOMEBUILDER@PROJECT_MENU_SIDER'
export const PROJECT = 'HOMEBUILDER@PROJECT'
export const PROJECT_INDEX = 'HOMEBUILDER@PROJECT_INDEX'
export const PROJECT_NEW = 'HOMEBUILDER@PROJECT_NEW'
export const PROJECT_UPDATE = 'HOMEBUILDER@PROJECT_UPDATE'